#!/bin/sh -e

# llvm ar patch
patch -p1 < llvm_ar.patch

# Stage 1: bootstrap muon using the bundled C sources.
./bootstrap.sh build-stage1

# Stage 2: muon built by the stage 1 bootstrap.
build-stage1/muon-bootstrap setup \
    -Dlibarchive=disabled \
    -Dlibcurl=disabled \
    -Dlibpkgconf=disabled \
    -Dman-pages=disabled \
    -Dmeson-docs=disabled \
    -Dmeson-tests=disabled \
    -Dreadline=builtin \
    -Dsamurai=enabled \
    -Dtracy=disabled \
    -Dui=disabled \
    -Dwebsite=disabled \
    build-stage2
ninja -C build-stage2

# Stage 3: final muon, built by itself.
build-stage2/muon setup \
    -Dlibarchive=disabled \
    -Dlibcurl=disabled \
    -Dlibpkgconf=disabled \
    -Dman-pages=disabled \
    -Dmeson-docs=disabled \
    -Dmeson-tests=disabled \
    -Dreadline=builtin \
    -Dsamurai=enabled \
    -Dtracy=disabled \
    -Dui=disabled \
    -Dwebsite=disabled \
    -Dprefix=/usr \
    build
ninja -C build

DESTDIR="$1" build/muon -C build install
ln -sf /usr/bin/muon "$1/usr/bin/meson"

