#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --with-threads \
    --without-modules \
    --with-magick-plus-plus \
    --with-bzlib \
    --with-zlib \
    --with-fontconfig \
    --with-freetype \
    --with-jpeg \
    --without-jxl \
    --with-pango \
    --without-x \
    --with-png \
    --with-webp \
    --without-xml \
    --without-perl
make
make DESTDIR="$1" install
