#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dfloat-approx=true \
    -Dcustom-modes=true \
    -Ddefault_library=shared \
    output

ninja -C output
ninja -C output install
