#!/bin/sh -e
export DESTDIR="$1"

# Muon bypass
#sed -i "s/_llvm_rtti = \['ON', 'YES'\].contains(dep_llvm.get_variable([^)]*))/_llvm_rtti = false/" meson.build
sed -i "s|dep_llvm.get_variable(cmake : 'LLVM_LIBRARY_DIR', configtool: 'libdir')|'/usr/lib'|" meson.build
sed -i "s/prog_bison = find_program('bison', required : false)/prog_bison = find_program('byacc', required : needs_flex_bison, disabler : true)\n  yacc_is_bison = false/" meson.build
sed -i "s/mod_wl = import('unstable-wayland')/mod_wl = import('wayland')/" meson.build
sed -i "s|dep_llvm.get_variable(cmake : 'LLVM_LIBRARY_DIR', configtool: 'libdir')|'/usr/lib'|" meson.build
sed -i \
    -e "s|mod_wl.find_protocol('fifo', state : 'staging', version : 1)|join_paths('/usr/share/wayland-protocols', 'staging', 'fifo', 'fifo-v1.xml')|" \
    -e "s|mod_wl.find_protocol('commit-timing', state : 'staging', version : 1)|join_paths('/usr/share/wayland-protocols', 'staging', 'commit-timing', 'commit-timing-v1.xml')|" \
    -e "s|mod_wl.find_protocol('linux-dmabuf', state : 'unstable', version : 1)|join_paths('/usr/share/wayland-protocols', 'unstable', 'linux-dmabuf', 'linux-dmabuf-unstable-v1.xml')|" \
    -e "s|mod_wl.find_protocol('presentation-time')|join_paths('/usr/share/wayland-protocols', 'stable', 'presentation-time', 'presentation-time.xml')|" \
    -e "s|mod_wl.find_protocol('tearing-control', state : 'staging', version : 1)|join_paths('/usr/share/wayland-protocols', 'staging', 'tearing-control', 'tearing-control-v1.xml')|" \
    -e "s|mod_wl.find_protocol('linux-drm-syncobj', state : 'staging', version : 1)|join_paths('/usr/share/wayland-protocols', 'staging', 'linux-drm-syncobj', 'linux-drm-syncobj-v1.xml')|" \
    -e "s|mod_wl.find_protocol('color-management', state : 'staging', version : 1)|join_paths('/usr/share/wayland-protocols', 'staging', 'color-management', 'color-management-v1.xml')|" \
    src/loader/meson.build



sed '/rust_std=2021/d' meson.build > _
mv -f _ meson.build

sed -i "s/version *: *'> *2\.3'//" meson.build

find src -type f \( -name '*.y' -o -name '*.yy' \) -exec sed -i \
        -e 's/%define[[:space:]]\+api\.pure[^$]*/%pure-parser/' \
            -e '/%define/d' \
                {} +
                    find src -name meson.build -exec sed -i \
        "s|'--defines=@OUTPUT1@'|'-H', '@OUTPUT1@'|g" {} +                    
pkg-config --exists libglvnd || glvnd_enabled=false

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dgles1=true \
    -Dgles2=true \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dcpp_rtti=false \
    -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
    -Dvulkan-drivers='' \
    -Dcpp_link_args='-fuse-ld=lld -lc++abi' \
    output

sed -i -e 's/ -Wno-deprecated//g' -e 's/--defines=\([^ ]*\)/-H \1/g' output/build.ninja

ninja -C output
ninja -C output install
