#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dgtk=disabled \
    -Dmmx=disabled \
    -Dsse2=disabled \
    -Dssse3=disabled \
    output

ninja -C output
ninja -C output install
