#!/bin/sh -e

export DESTDIR="$1"

# Muon 
sed -i 's/, sources: protocols_headers//' meson.build
sed -i "s/'main.c'/'main.c', protocols_headers/" meson.build

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    output

ninja -C output
ninja -C output install
